---

- name: systemd-resolved | remove resolvconf
  tags:
    - resolver
    - package
  package:
    state: absent
    purge: yes
    name: 
      - resolvconf
      - openresolv

- name: systemd-resolved | glibc NSS module
  tags:
    - resolver
    - package
  package:
    name: libnss-resolve

- name: systemd-resolved | config
  tags:
    - resolver
    - config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart resolved

- name: systemd-resolved | check resolvectl
  stat:
    path: /usr/bin/resolvectl
  register: ctl_stat

- name: systemd-resolved | emulate resolvconf
  tags:
    - resolvconf
  file:
    src: /usr/bin/resolvectl
    dest: /sbin/resolvconf
    state: link
  when: ctl_stat.stat.exists is defined and ctl_stat.stat.exists

- name: systemd-resolved | dhclient hook
  tags:
    - hook
  copy:
    src: resolvconf
    dest: /etc/dhcp/dhclient-enter-hooks.d/
  when: ctl_stat.stat.exists is defined and ctl_stat.stat.exists

- name: systemd-resolved | service
  tags:
    - resolver
    - service
  service:
    name: systemd-resolved
    state: started
    enabled: yes
#  notify: use resolved

- name: systemd-resolved | Stat /etc/resolv.conf
  stat:
    path: /etc/resolv.conf
  register: etc_resolv_conf

- name: systemd-resolved | Remove /etc/resolv.conf if not symbolic link
  become: yes
  file:
    path: /etc/resolv.conf
    state: absent
  when: etc_resolv_conf.stat.islnk is defined and etc_resolv_conf.stat.islnk == False

- name: systemd-resolved | Create symlink /etc/resolv.conf
  tags:
    - resolvconf
  file:
    src: ../run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: etc_resolv_conf.stat.islnk is undefined or etc_resolv_conf.stat.islnk == False
