---

- name: systemd-resolved | remove resolvconf
  tags:
    - resolver
    - package
  package:
    state: absent
    purge: yes
    name: 
      - resolvconf
      - openresolv

- name: systemd-resolved | glibc NSS module
  tags:
    - resolver
    - package
  package:
    name: libnss-resolve
  when: 'dns' not in group_names

- name: systemd-resolved | nsswitch.conf
  replace:
    path: /etc/nsswitch.conf
    regexp: 'resolve (\[.*\])?'
    replace: ""
  when: 'dns' in group_names

- name: systemd-resolved | config
  tags:
    - resolver
    - config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart resolved

- name: systemd-resolved | set /etc/resolv.conf
  tags:
    - resolver
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: systemd-resolved | service
  tags:
    - resolver
    - service
  service:
    name: systemd-resolved
    state: started
    enabled: yes
